name: Release

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Attest release assets
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            main.js
            styles.css
            manifest.json
